### ISSUE TITLE
Doc strings in doltpy.core end abruptly

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/doltpy#13]
https://github.com/liquidata-inc/doltpy/blob/d40ba0701fe6c0dc0783be303586340a333c240b/doltpy/core/dolt.py#L105

https://github.com/liquidata-inc/doltpy/blob/d40ba0701fe6c0dc0783be303586340a333c240b/doltpy/core/dolt.py#L257

**Comment by timsehn** [comment]
https://github.com/liquidata-inc/doltpy/blob/d40ba0701fe6c0dc0783be303586340a333c240b/doltpy/core/dolt.py#L248

**Comment by oscarbatori** [comment]
This is resolved.
