### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by impredicative** [liquidata-inc/doltpy#29]
Is Python 3.8 supported? https://www.dolthub.com/docs/tutorials/installation/#doltpy says:
> We currently do not support Python versions higher than 3.7 due to an incompatibility with the MySQL Server connectors we are using.

Well, this is really bad, and this means I can't use this package. It's not a sustainable approach. The beta of 3.9 is already out.

In any case, shouldn't `setup.py` document which versions of Python are required for this package?

**Comment by oscarbatori** [comment]
Agreed, we need support for 3.8. We are currently in a Doltpy sprint (of sorts) and I will add this to the list.

**Comment by oscarbatori** [comment]
@impredicative thanks for this, we now support 3.8 as we were able to verify the new `mysql-connector` works with 3.7 as well as 3.8.

**Comment by impredicative** [comment]
@oscarbatori Can the obsolete note at https://www.dolthub.com/docs/tutorials/installation/#doltpy_conclusion be updated to state the range of Python versions that are now supported? It currently says:

> We currently do not support Python versions higher than 3.7 due to an incompatibility with the MySQL Server connectors we are using.

**Comment by oscarbatori** [comment]
Good catch, I will update that @impredicative.

Thanks.

**Comment by oscarbatori** [comment]
New docs:
```
Doltpy supports Python 3.7 and 3.8. Older versions of Python may work, though they are not tested. If you find any issues with Doltpy, we'd be grateful for an issue on our GitHub page.
```
