### ISSUE TITLE
Go API?

### ISSUE THREAD

**Issue by jimsmart** [liquidata-inc/doltpy#55]
Hi,

Nice work on Dolt and this Python API.

Is there a clean and simple Go API for performing Dolt operations and getting results back?

Obviously, the backend is Go, but I don't see an easily accessible API for a client program to utilise. Perhaps I overlooked something?

Apologies if this is not the best place to ask this question.

Thanks!

**Comment by timsehn** [comment]
@reltuk @bheni? 

The Go API is not polished but there's a way to get at it. We can polish it if you have a use case.

**Comment by reltuk** [comment]
Yeah, we don't currently have a Go API that's expected to be stable across Dolt releases. Instead, the CLI and sql-server interfaces are (pretty) stable, although we're iterating towards better compliance with MySQL and Git and so sometimes we change things in backwards incompatible ways. The best way to interface with Dolt from Golang currently is to spawn a sql-server and connect to it using `database/sql`. Maybe not the most ergonomic approach for your use case...how painful does it sound?

**Comment by oscarbatori** [comment]
@jimsmart let us know if this answers your question.

**Comment by jimsmart** [comment]
I'm conducting a feasibility study: client has a ETL-type workflow, including merging of datasets with a human-in-the-loop, but client is not themselves technically-minded enough to use command line tools nor write SQL, so we plan to build a UI of some kind, based around domain specific presentation regarding the dataset. Obviously, Dolt seems to offer pretty much the back-end functionality we need, so it might not be in our best interests to attempt to manually replicate this. And we are already using Go for other tools in the pipeline. 

I don't mind too much about your proposal not being the most ergonomic, wrapping the CLI was already on my list as a possibility, and connecting via SQL is certainly do-able — and not something I had considered, thanks for the tip.
