### ISSUE TITLE
Users confused by dolt.engine. Should have a public dolt.get_engine()

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/doltpy#86]
It's also in the docs as `get_engine()`.

https://www.dolthub.com/docs/tutorials/reading-from-dolt/#python

We need to fix this asap.

**Comment by timsehn** [comment]
https://github.com/liquidata-inc/ld/pull/5001

Docs fix.

**Comment by oscarbatori** [comment]
This is bug, and it's now been resolved.
